name: UnitTest

on:
    push:
        branches: ["**"]

jobs:
    build:
        runs-on: macOS-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Swift
              uses: swift-actions/setup-swift@v2

            - name: Run Tests
              run: swift test
              working-directory: ./BuildTools