name: UnitTest

on:
    push:
        branches: ["**"]

jobs:
    build:
        runs-on: macOS-15
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Xcode
              run: sudo xcode-select -s /Applications/Xcode_16.4.0.app

            - name: Install dependencies
              run: xcodebuild -resolvePackageDependencies -project QiitaViewer.xcodeproj

            - name: Run tests
              run: |
                xcodebuild test \
                  -project QiitaViewer.xcodeproj \
                  -scheme QiitaViewer \
                  -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5'